name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to Server
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@18.205.242.28 <<EOF
            # Navigate to the deployment directory
            cd /home/ubuntu/taletinker
            
            # Fetch and reset code
            git fetch origin
            git reset --hard origin/main
            
            # Activate virtual environment
            source venv/bin/activate
            
            # Install requirements
            pip install -r requirements.txt
            
            # Django commands
            python manage.py migrate --noinput || { echo "Migrations failed"; exit 1; }
            python manage.py collectstatic --noinput || { echo "Collectstatic failed"; exit 1; }
            
            # Restart the server
            sudo systemctl restart taletinker
          EOF
